feat: switch to uv and use brew bundle for vscode/go/krew
Signed-off-by: lvlcn-t <75443136+lvlcn-t@users.noreply.github.com>

diff --git a/run_once_before_02-config-wizard.sh.tmpl b/run_once_before_02-config-wizard.sh.tmpl
--- a/run_once_before_02-config-wizard.sh.tmpl
+++ b/run_once_before_02-config-wizard.sh.tmpl
@@ -14,23 +14,13 @@ __config_wizard() {
     exit 1
   }
 
-  # pipx installs the poetry binary into ~/.local/bin so
-  # we need to ensure that this directory is in the PATH.
-  export PATH="${PATH}:${HOME}/.local/bin"
-  which poetry >/dev/null || {
-    echo "Error: Poetry is not installed. Please install Poetry in ${HOME}/.local/bin or ensure it is in your PATH."
+  which uv >/dev/null || {
+    echo "Error: uv is not installed. Please install uv and ensure it is in your PATH."
     exit 1
   }
-
-  echo "📦 Installing dependencies..."
-  poetry install || {
-    echo "Error: Could not install dependencies. Please ensure Poetry is installed and configured correctly."
-    exit 1
-  }
-  echo "📦 Dependencies installed."
 
   echo "🧙‍♂️ Running configuration wizard..."
-  poetry run python3 scripts/configure.py || {
+  uv run python3 scripts/configure.py || {
     echo "Error: Configuration wizard failed. Please check the output for details."
     exit 1
   }
