refactor: simplify pre-install-deps script

diff --git a/scripts/run_once_before_install-deps.zsh.tmpl b/scripts/run_once_before_install-deps.zsh.tmpl
--- a/scripts/run_once_before_install-deps.zsh.tmpl
+++ b/scripts/run_once_before_install-deps.zsh.tmpl
@@ -1,106 +1,36 @@
 #!/bin/bash
 
 # (c) 2024 lvlcn-t - pre-install-deps
-# This script is consumed by chezmoi to install dependencies once before running the dotfiles
-# It is idempotent and can be run multiple times without causing issues
+# This script is consumed by chezmoi to install dependencies once before running the dotfiles.
+# It is idempotent and can be run multiple times without causing issues.
 
 {{ if eq .chezmoi.os "linux" -}}
 
-# install_eza installs the eza command line tool for file management
-install_eza(){
-  # TODO: check if the keyring is already installed
-  sudo mkdir -p /etc/apt/keyrings
-  wget -qO- https://raw.githubusercontent.com/eza-community/eza/main/deb.asc | sudo gpg --dearmor -o /etc/apt/keyrings/gierens.gpg
-  echo "deb [signed-by=/etc/apt/keyrings/gierens.gpg] http://deb.gierens.de stable main" | sudo tee /etc/apt/sources.list.d/gierens.list
-  sudo chmod 644 /etc/apt/keyrings/gierens.gpg /etc/apt/sources.list.d/gierens.list
-  sudo apt update
-  sudo apt install -y eza
+# keyring_installed checks if a keyring is installed
+keyring_installed() {
+  [ -f "/etc/apt/keyrings/$1" ]
 }
 
-# install_docker installs the docker engine
-install_docker(){
-  # TODO: check if the keyring is already installed
-  sudo apt update
-  sudo apt install ca-certificates curl
-  sudo install -m 0755 -d /etc/apt/keyrings
-  sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
-  sudo chmod a+r /etc/apt/keyrings/docker.asc
-  echo \
-  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
-  $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
-  sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
-  sudo apt update
-  sudo apt install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
+# install_or_update installs/updates a package if it does not exist
+install_or_update() {
+  sudo apt install -y "$1"
 }
 
-# install neovim installs the neovim text editor
-install_neovim(){
-  sudo add-apt-repository ppa:neovim-ppa/stable
-  sudo apt-get update
-  sudo apt-get install neovim
-}
-
-# install_go installs the latest version of the go programming language
-install_go(){
-  go_version=$(curl -fsSL "https://go.dev/dl/?mode=json" | jq -r '.[0].version')
-  curl -LO https://golang.org/dl/$go_version.linux-amd64.tar.gz
-  sudo rm -rf /usr/local/go && sudo tar -C /usr/local -xzf $go_version.linux-amd64.tar.gz
-  rm $go_version.linux-amd64.tar.gz
-}
-
-# validate_kubectl installs the kubectl binary and validates it
-# Returns 0 if the kubectl binary is valid, 1 otherwise
-validate_kubectl() {
-  for attempt in 1 2 3; do
-    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
-    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"
-    echo "$(cat kubectl.sha256)  kubectl" | sha256sum --check
-    if [ $? -eq 0 ]; then
-      rm -f kubectl.sha256
-      return 0
-    fi
-    if [ $attempt -eq 3 ]; then
-      echo "Error: Failed to validate kubectl binary."
-      rm -f kubectl kubectl.sha256
-      return 1
-    fi
-    echo "Retrying..."
-  done
-}
-
-# install_kubectl installs the kubectl binary
-install_kubectl(){
-  validate_kubectl
-  if [ $? -ne 0 ]; then
-    echo "Error: Failed to validate kubectl binary."
-    return 1
+# add_repo adds an apt repository to the system
+add_repo() {
+  local repo=$1
+  local keyring=$2
+  local url=$3
+  local components=$4
+  if ! grep -q "^deb .*$url" /etc/apt/sources.list /etc/apt/sources.list.d/*; then
+    echo "Adding repository: $repo"
+    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/$keyring] $url $components" | sudo tee /etc/apt/sources.list.d/$repo.list
+    sudo apt update
+  else
+    echo "Repository $repo already exists."
   fi
-  sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
-  rm kubectl
 }
 
-# install_helm installs the helm binary
-install_helm(){
-  curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
-}
-
-# install_gh_cli installs the gh command line tool
-install_gh_cli(){
-  # TODO: check if the keyring is already installed
-  sudo mkdir -p -m 755 /etc/apt/keyrings && wget -qO- https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
-  && sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
-  && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
-  && sudo apt update \
-  && sudo apt install gh -y
-}
-
-# install_nvm installs the node version manager
-install_nvm(){
-  PROFILE=/dev/null bash -c 'curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash'
-}
-
-# TODO: do this with chezmoi ({{- $email := promptStringOnce . "email" "Email address" -}})
-# Prompt user for HTTP/HTTPS Proxy
 if [ -z "$HTTP_PROXY" ] && [ -z "$HTTPS_PROXY" ]; then
   read -p "Do you need to set an HTTP/HTTPS Proxy? (y/n): " proxy_required
   if [[ $proxy_required == "y" ]]; then
@@ -113,71 +43,95 @@ fi
 
 sudo apt update
 if ! command -v git &> /dev/null; then
-  sudo add-apt-repository ppa:git-core/ppa -y
+  sudo add-apt-repository ppa:git-core/ppa -y -u > /dev/null 2>&1
 else
   installed_git_version=$(git --version | awk '{print $3}')
   required_git_version="2.36.0"
   
   if [[ $installed_git_version < $required_git_version ]]; then
-    sudo add-apt-repository ppa:git-core/ppa -y
+    sudo add-apt-repository ppa:git-core/ppa -y -u > /dev/null 2>&1
   fi
 fi
-sudo apt update && sudo apt install -y build-essential software-properties-common curl gpg git neovim tree wget zsh
 
+necessary_packages=(git curl wget zsh tree ca-certificates software-properties-common gpg)
+for package in "${necessary_packages[@]}"; do
+  install_or_update "$package"
+done
+
+# Install brew
 if ! command -v brew &> /dev/null; then
   /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
 fi
-
 brew bundle install --file={{ .chezmoi.sourceDir }}/Brewfile
 
-if ! command -v zplug &> /dev/null
-then
+# Create the keyrings directory
+sudo install -m 0755 -d /etc/apt/keyrings
+
+if ! command -v eza &> /dev/null; then
+  if ! keyring_installed "eza.gpg"; then
+    wget -qO- https://raw.githubusercontent.com/eza-community/eza/main/deb.asc | sudo gpg --dearmor -o /etc/apt/keyrings/eza.gpg
+  fi
+  add_repo "eza" "eza.gpg" "http://deb.gierens.de" "stable main"
+  install_or_update "eza"
+fi
+
+if ! command -v docker &> /dev/null; then
+  if ! keyring_installed "docker.asc"; then
+    sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc && sudo chmod a+r /etc/apt/keyrings/docker.asc
+  fi
+  add_repo "docker" "docker.asc" "https://download.docker.com/linux/ubuntu" "$(. /etc/os-release && echo "$VERSION_CODENAME") stable"
+  docker_packages=(docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin)
+  for package in "${docker_packages[@]}"; do
+    install_or_update "$package"
+  done
+fi
+
+if ! command -v nvim &> /dev/null; then
+  sudo add-apt-repository ppa:neovim-ppa/stable -y -u > /dev/null 2>&1
+  install_or_update "neovim"
+fi
+
+if ! command -v zplug &> /dev/null; then
   curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh
 fi
 
-if ! command -v eza &> /dev/null
-then
-  install_eza
+go_version=$(curl -fsSL "https://go.dev/dl/?mode=json" | jq -r '.[0].version')
+if ! go version | grep -q "$go_version"; then
+  curl -fsSL -LO "https://golang.org/dl/$go_version.linux-amd64.tar.gz"
+  sudo tar -C /usr/local -xzf "$go_version.linux-amd64.tar.gz"
+  rm "$go_version.linux-amd64.tar.gz"
+else
+  echo "Go $go_version is already installed."
 fi
 
-if ! command -v docker &> /dev/null
-then
-  install_docker
-fi
-
-if ! command -v nvim &> /dev/null
-then
-  install_neovim
-fi
-
-if ! command -v go &> /dev/null
-then
-  install_go
-fi
-
-if ! command -v kubectl &> /dev/null
-then
-  install_kubectl
-  if [ $? -ne 0 ]; then
-    echo "Error: Failed to install kubectl binary."
+if ! command -v kubectl &> /dev/null; then
+  curl -fsSL -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
+  validate_checksum "kubectl" "https://dl.k8s.io/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"
+  if [ $? -eq 0 ]; then
+    sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
+  else
+    echo "Kubectl checksum validation failed. kubectl was not installed."
   fi
+  rm kubectl
 fi
 
-if ! command -v helm &> /dev/null
-then
-  install_helm
+if ! command -v helm &> /dev/null; then
+  curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
 fi
 
-if ! command -v gh &> /dev/null
-then
-  install_gh_cli
+if ! command -v gh &> /dev/null; then
+  if ! keyring_installed "github-cli.gpg"; then
+    wget -qO- https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo tee /etc/apt/keyrings/github-cli.gpg && sudo chmod go+r /etc/apt/keyrings/github-cli.gpg
+  fi
+  add_repo "github-cli" "github-cli.gpg" "https://cli.github.com/packages" "stable main"
+  install_or_update "gh"
 fi
 
-if ! command -v nvm &> /dev/null
-then
-  install_nvm
+if ! command -v nvm &> /dev/null; then
+  PROFILE=/dev/null bash -c 'curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash'
 fi
-
 {{- end }}
 
-# TODO: install brew bundle from chezmoi.sourceDir/Brewfile
+{{ if eq .chezmoi.os "darwin" -}}
+# TODO: Implement the installation of dependencies for macOS / when implementing this, everything for linux can be also done with brew
+{{- end }}
